[pytest]
addopts = --alluredir=output/allure-results --html=output/report.html --self-contained-html
testpaths = tests/
python_files = test_*.py
console_output_encoding = utf-8
# 失败用例重试 1 次
reruns = 1
#  markers 定义
markers =
    login: login module tests
    monitor: monitor module tests
    monitor_center: monitor_center module tests
    workbench: workbench module tests
    content_publish: content_publish module tests
